service: dynamodb-crud
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment: ${file(./src/config/env.json)}
  iam:
    role:
      statements: ${file(./src/config/db.iam.role.yml)}

custom:
  tableName: ${self:provider.environment.DYNAMODB_TABLE}
  dbWriteCapacityUnits: ${self:provider.environment.DbWriteCapacityUnits}
  dbReadCapacityUnits: ${self:provider.environment.DbReadCapacityUnits}

resources:
  Resources: ${file(./src/config/dynamo.users.table.yml)}

functions:
  create-user:
    handler: src/factory.create
    events:
      - httpApi:
          path: /users
          method: post
  # update-user:
  #   handler: index.update
  #   events:
  #     - httpApi:
  #         path: /users
  #         method: patch
  delete-user:
    handler: src/factory.deleteUser
    events:
      - httpApi:
          path: /users/{id}
          method: delete
  find-users:
    handler: src/factory.findAllUsers
    events:
      - httpApi:
          path: /users
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-offline
