service: dynamodb-crud
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment: ${file(./config/env.json)}
  iamRoleStatements: $file(./config/db.iam.role.yml)

custom:
  tableName: ${self:provider.environment.DbTableName}
  dbWriteCapacityUnits: ${self:provider.environment.DbWriteCapacityUnits}
  dbReadCapacityUnits: ${self:provider.environment.DbReadCapacityUnits}

resources:
  Resources: ${file(./config/dynamo.users.table.yml)}

functions:
  dynamodb-crud:
    handler: index.create
    events:
      - httpApi:
          path: /users
          method: post

plugins:
  - serverless-plugin-typescript
  - serverless-offline
