service: dynamodb-crud
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment: ${file(./src/config/env.json)}
  iam:
    role:
      statements: ${file(./src/config/db.iam.role.yml)}

custom:
  tableName: ${self:provider.environment.DYNAMODB_TABLE}
  dbWriteCapacityUnits: ${self:provider.environment.DbWriteCapacityUnits}
  dbReadCapacityUnits: ${self:provider.environment.DbReadCapacityUnits}

resources:
  Resources: ${file(./src/config/dynamo.users.table.yml)}

functions:
  create-user:
    handler: index.create
    events:
      - httpApi:
          path: /users
          method: post
  update-user:
    handler: index.update
    events:
      - httpApi:
          path: /users
          method: patch
  delete-user:
    handler: index.delete
    events:
      - httpApi:
          path: /users
          method: delete
  find-user:
    handler: index.find
    events:
      - httpApi:
          path: /users
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-offline
