Table:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:custom.tableName}
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: nameUser
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
      - AttributeName: nameUser
        KeyType: RANGE

    ProvisionedThroughput:
      ReadCapacityUnits: ${self:custom.dbReadCapacityUnits}
      WriteCapacityUnits: ${self:custom.dbWriteCapacityUnits}
